name: Deploy WebApp Container

on:
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./tf

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./tf

    - name: Generate unique name
      id: unique_name
      run: echo "name=webapp-$(date +%s)" >> $GITHUB_OUTPUT

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="webapp_name=${{ steps.unique_name.outputs.name }}"
      working-directory: ./tf
      env: 
             TF_VAR_docker_username: ${{ secrets.DOCKER_USERNAME }}
             TF_VAR_docker_password: ${{ secrets.DOCKER_PASSWORD }}
             TF_VAR_docker_image: "kdetony/webapp:0.1"
             TF_VAR_webapp_name: "webappcnt-$(date +%s)"  #hora
